before_script:
  - pip install -r requirements.txt

pylint:
  stage: test
  needs: []
  image: python:3
  script:
    - pip install pylint
    - pylint harbor-image-replication-manager.py
  allow_failure: true


flake8:
  stage: test
  needs: []
  image: python:3
  script:
    - pip install flake8
    - flake8 harbor-image-replication-manager.py
  allow_failure: true
